name = "my-site"
type = "javascript"

[build]
command = "npm run build"
upload.format = "service-worker"
upload.main = "./dist/assets/index-XXXX.js" # â† this must match actual output

[site]
bucket = "./dist"
entry-point = "workers-site"
